config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'events#index'

  resources :events do
    
  end

  resources :users do
    resources :orders

    member do
      get :become_a_local_pal
    end
  end

  namespace :admin do
    resources :users
    resources :orders
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :interestings
  has_many :interests, :through => :interestings

  has_many :user_language_ships
  has_many :languages, :through => :user_language_ships

  has_many :user_role_ships
  has_many :roles, :through => :user_role_ships

  has_many :orders


  def self.from_omniauth(auth)
    # Case 1: Find existing user by facebook uid
    user = User.find_by_fb_uid( auth.uid )
    if user
      user.fb_token = auth.credentials.token
      #user.fb_raw_data = auth
      user.skip_confirmation! 
      user.save!
      return user
    end

    # Case 2: Find existing user by email
    existing_user = User.find_by_email( auth.info.email )
    if existing_user
      existing_user.fb_uid = auth.uid
      existing_user.fb_token = auth.credentials.token

      if !existing_user.name
        existing_user.name = auth.info.name
      end 
      
      if !existing_user.facebook_url
        existing_user.facebook_url = auth.info.urls.Facebook
      end 

      if !existing_user.head_shot
        existing_user.head_shot = auth.info.image
      end
      
      #existing_user.fb_raw_data = auth
      existing_user.skip_confirmation! 
      existing_user.save!
      return existing_user
    end

    # Case 3: Create new password
    user = User.new
    user.fb_uid = auth.uid
    user.fb_token = auth.credentials.token
    user.email = auth.info.email
    user.name = auth.info.name
    user.facebook_url = auth.info.urls.Facebook
    user.head_shot = auth.info.image
    user.password = Devise.friendly_token[0,20]
    #user.fb_raw_data = auth
    user.skip_confirmation! 
    user.save!
    return user
  end

  def self.is_tour_guide
    users = User.all
    ids=[]

    users.each do |user|
      if user.roles.pluck('name').include? "tour_guide"
        ids.push(user.id)
      end
    end

    User.where(:id => ids)
  end

  def Mandarin
  end
  def English
  end
  def Japanese
  end
  def Cantonese
  end
  def Taiwanese
  end
  def Korean
  end
  def Spanish
  end
  def French
  end
  def German
  end
  def others
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  layout "admin"

  before_action :correct_user, only: [:edit, :index]
  before_action :authenticate_user!
  before_action :is_admin?

  def index
    @users = User.all
  end

  def update
    id = params["edit_user"]
    user = User.find(id)
    if user.update(user_params)
      flash[:notice] = "更新成功!"
      redirect_to admin_users_path
    end
  end

  private

  def is_admin?
    @user = current_user
    @user.roles.pluck('name').include? "admin"
  end

  def user_params
    params.require(:user).permit(:role_ids=>[]
                                )
  end

  def correct_user
    @user = current_user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout "application"

  before_action :correct_user, only: [:edit, :update]
  before_action :authenticate_user!, except: [:index, :clause, :contact, :send_mail]
  before_action :find_user, only: [:show, :edit, :update, :upload]
  
  def index
    @users = User.all
  end

  def show
    # @photos = @user.photos.all
  end

  def edit
  end

  def update
    if user_language_params
      for language in user_language_params.keys
        language_id = Language.all.find_by(name: language).id
        level = user_language_params[language]
        
        if @user.user_language_ships.find_by(language_id: language_id)
          ship = @user.user_language_ships.find_by(language_id: language_id)
          ship.update(:level => level)
        else
          @user.user_language_ships.create(language_id: language_id, level: level)
        end
      end
    end
    
    if @user.update(user_params)
      flash[:notice] = "更新成功!"
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def destroy
  end

  def become_a_local_pal
    
  end

  private

  def find_user
    @user = User.find_by_id(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :nick_name, :profession, :head_shot,
                                 :description_English, :description_Chinese,
                                 :availability, :travel_footprints,
                                 :familiar_areas, :facebook_url, 
                                 :country, :phone_number, :birthday, :gender,
                                 :social_media_id,
                                 :interest_ids =>[],
                                 :language_ids =>[],
                                )
  end

  def user_language_params
    params.require(:user).permit( :Mandarin, :English, :Japanese, :Cantonese,
                                  :Taiwanese, :Korean, :Spanish, :French,
                                  :German, :others,
                                )
  end

  def correct_user
    @user = current_user
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/become_a_local_pal.html.erb
<div class="col-md-offset-3 col-md-6">
	<h2 style="text-align: center">Wanna become a Local Pal?</h2>
	<p>JDpal allows every Local Pal to show off the city he/she lives in and make friends. A Local Pal can set his/her own available time slots and accept or turn down a visitor request before formal engagement. JDpal always maintains a strong support network and provides essential resources for our qualified Local Pals. So join us!</p>

	<h3 style="text-align: center">
		<a  href="http://goo.gl/forms/8WEl4Fzd3e">Join us!</a>
	</h3>
</div>

<div class="clearfix"></div>

<div style="background-color: #FAACB4; text-align: center;  height: 66px">
	<h3 style="line-height: 66px; color: white;">How it works</h3>
</div>

<div style="background-color: #F275A7; text-align: center; color: white;">
	<h2 style="margin-top: 0;">List on JDpal</h2>
	<p>Fill out the form and we will arrange an interview with you. Qualified Local Pal would be listed on JDpal for Free</p>

	<h1><i class="fa fa-angle-double-down" aria-hidden="true"></i></h1>

	<h2>Communicate with your visitor</h2>
	<p>Contact your visitor to cater to his/her needs, and create a private plan customized for your visitor</p>

	<h1><i class="fa fa-angle-double-down" aria-hidden="true"></i></h1>

	<h2>Host and Enjoy</h2>
</div>

app/views/users/edit.html.erb
<div class="col-md-6 ">
  <%=form_for @user, :url => user_path(current_user,current_user), :method => :PATCH do |f| %>
    <%= f.label :name, "姓名" %>
    <%= f.text_field :name, class: 'form-control'%>

    <%= f.label :nick_name, "暱稱" %>
    <%= f.text_field :nick_name, class: 'form-control' %>

    <%= f.label :gender, "Gender" %> <br>
    <%= f.radio_button :gender, "M" %>  <i style="color:blue;" class="fa fa-venus" aria-hidden="true">(Male)</i>
    <br>
    <%= f.radio_button :gender, "F"%>  <i style="color:red;" class="fa fa-mars" aria-hidden="true">(Female)</i>
    <br>
    <%= f.radio_button :gender, "others" %>  <i class="fa fa-genderless" aria-hidden="true">(Others)</i><br>
    <br>

    <%= f.label :description_English, "個人敘述(英文)" %>
    <%= f.text_area :description_English, class: 'form-control', rows: '15'%>

    <%= f.label :description_Chinese, "個人敘述(中文)" %>
    <%= f.text_area :description_Chinese, class: 'form-control', rows: '15' %>

    <%= f.label :profession, "職業" %>
    <%= f.text_field :profession, class: 'form-control' %>

    <%= f.label :phone_number, "Phone Number" %>
    <%= f.text_field :phone_number, class: 'form-control' %>

    <%= f.label :social_media_id, "Social Media ID" %>
    <%= f.text_field :social_media_id, class: 'form-control'%>

    <%= f.label :birthday, "birthday" %>
    <%= f.date_field :birthday, class: 'form-control' %>

    <%= f.label :country, "Country" %>
    <%= f.text_field :country, class: 'form-control' %>

    <%= f.label :availability, "空閑時間" %>
    <%= f.text_field :availability, class: 'form-control' %>

    <div class="form-group user-checklist">
        <h3>Areas of Interests <span style="color: red;">*</span></h3> 
        <p>興趣領域</p>
        <%= f.collection_check_boxes(:interest_ids, Interest.all, :id, :name)%>
    </div>

    <div class="form-group user-checklist">
        <h3>Languages <span style="color: red;">*</span></h3> 
        <p>語言</p>
        <table class="table">
            <tr>
                <td class="col-md-3"> </td>
                <% LanguageLevel.all.each do |level|%>
                    <td><%= level.name %> <%= level.chinese_name%></td>        
                <% end%>
            </tr>
            <% Language.all.each do |lan|%>
                <tr>
                    <td class="col-md-3"><%= lan.name%><%= lan.chinese_name%></td> 
                    <% LanguageLevel.all.each do |level|%>
                        <td>
                            <%= f.radio_button lan.name, level.name, checked: 
                            if @user.user_language_ships.find_by(language_id: lan.id,
                                                                 level: level.name 
                                                                    )
                                true
                            else
                                false
                            end
                            %>
                        </td>        
                    <% end%>
                </tr>
            <% end %>
        </table>
    </div>

    <%= f.label :travel_footprints, "你曾經去過哪些地方？" %>
    <%= f.text_area :travel_footprints, class: 'form-control', rows: '5' %>

    <%= f.label :familiar_areas, "熟悉的區域" %>
    <%= f.text_area :familiar_areas, class: 'form-control', rows: '5' %>

    <br>
    <%= f.submit "確認", class: "btn btn-primary form-control" %>
  <%end%>
</div>

<style type="text/css">

.user-checklist input[type="checkbox"] {
  display: inline-block;
  width: 5%;
  font-size: 16px;
}

.user-checklist input[type="checkbox"] + label {
  display: inline-block;
  width: 95%;
  font-size: 16px;
}
</style>

app/views/users/index.html.erb
Users
<div class="container">
<div class="row">
  <div class="col-md-10">
    <table class="table">
      <tr>
        <td>head_shot</td>
        <td>name</td>
        <td>email</td>

      </tr>
      <% @users.each do |user|%>
        <tr>
          <td><%= image_tag("#{user.head_shot}") %></td>
          <td><%= link_to user.name, user_path(user)%></td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
    </table> 
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="col-md-12 ">
  <% if current_user == @user%>
    <div><%= link_to "edit", edit_user_path(@user)%></div>
  <% end %>

  <%= link_to user_path(@user), class: "col-md-12" do%>
    <%= image_tag (@user.head_shot), style: "width: 80px; height: 80px; display: inline; border-radius: 10px; position: relative; right: 10px; margin:10px;"%>
  <%end%>

  <hr>
  <div id="user_about" class="col-md-6 col-md-offset-3">
    <h4>About <%= @user.name%></h4>
    <p><%= simple_format(@user.description_English) %></p>
    <p><%= simple_format(@user.description_Chinese) %></p>

    <hr>

    <div id="user_detail">
      <div class="row">
        <p class="col-md-4">Interests</p>
        <p class="col-md-8">
          <% @user.interests.each do |i|%>
            <%= i.name%>/
          <% end %>
        </p>
        <hr>
      </div>
      <div class="row">
        <p class="col-md-4">Profession</p>
        <p class="col-md-8"><%= @user.profession%></p>
        <hr>
      </div>
      <div class="row">
        <p class="col-md-4">Languages</p>
        <p class="col-md-8">
          <% @user.languages.each do |language|%>
            <% if @user.user_language_ships.find_by(:language_id => language.id).level =="Fluent" %>
              <%= language.name%>
              (Fluent)
              /
            <% end %>
          <% end %>
          <% @user.languages.each do |language|%>
            <% if @user.user_language_ships.find_by(:language_id => language.id).level =="Intermediate" %>
              <%= language.name%>
              (Intermediate)
              /
            <% end %>
          <% end %>
        </p>
        <hr>
      </div>
      <div class="row">
        <p class="col-md-4">familiar_areas</p>
        <p class="col-md-8"><%= @user.familiar_areas%></p>
        <hr>
      </div>
      <div class="row">
        <p class="col-md-4">availability</p>
        <p class="col-md-8"><%= @user.availability%></p>
        <hr>
      </div>
      <div class="row">
        <p class="col-md-4">travel_footprints</p>
        <p class="col-md-8"><%= @user.travel_footprints%></p>
        <hr>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-12">
          <%=link_to "Request", new_user_order_path(@user), :class => "btn btn-warning btn-lg col-md-12"%>
        </div>
      </div>
      <hr>
    </div>
  </div>
  <div id="user_about" class="col-md-3">
    <% if current_user && @user == current_user%>
      <%= link_to "My Order", user_orders_path(@user), :class => "btn btn-success btn-lg" %>
    <% end %>
  </div>    
</div>

  