config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'events#index'

  resources :events do
    
  end

  resources :users do
    resources :orders

    member do
      get :become_a_local_pal
    end
  end

  namespace :admin do
    resources :users
    resources :orders
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :interestings
  has_many :interests, :through => :interestings

  has_many :user_language_ships
  has_many :languages, :through => :user_language_ships

  has_many :user_role_ships
  has_many :roles, :through => :user_role_ships

  has_many :orders


  def self.from_omniauth(auth)
    # Case 1: Find existing user by facebook uid
    user = User.find_by_fb_uid( auth.uid )
    if user
      user.fb_token = auth.credentials.token
      #user.fb_raw_data = auth
      user.skip_confirmation! 
      user.save!
      return user
    end

    # Case 2: Find existing user by email
    existing_user = User.find_by_email( auth.info.email )
    if existing_user
      existing_user.fb_uid = auth.uid
      existing_user.fb_token = auth.credentials.token

      if !existing_user.name
        existing_user.name = auth.info.name
      end 
      
      if !existing_user.facebook_url
        existing_user.facebook_url = auth.info.urls.Facebook
      end 

      if !existing_user.head_shot
        existing_user.head_shot = auth.info.image
      end
      
      #existing_user.fb_raw_data = auth
      existing_user.skip_confirmation! 
      existing_user.save!
      return existing_user
    end

    # Case 3: Create new password
    user = User.new
    user.fb_uid = auth.uid
    user.fb_token = auth.credentials.token
    user.email = auth.info.email
    user.name = auth.info.name
    user.facebook_url = auth.info.urls.Facebook
    user.head_shot = auth.info.image
    user.password = Devise.friendly_token[0,20]
    #user.fb_raw_data = auth
    user.skip_confirmation! 
    user.save!
    return user
  end

  def self.is_tour_guide
    users = User.all
    ids=[]

    users.each do |user|
      if user.roles.pluck('name').include? "tour_guide"
        ids.push(user.id)
      end
    end

    User.where(:id => ids)
  end

  def Mandarin
  end
  def English
  end
  def Japanese
  end
  def Cantonese
  end
  def Taiwanese
  end
  def Korean
  end
  def Spanish
  end
  def French
  end
  def German
  end
  def others
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  layout "admin"

  before_action :correct_user, only: [:edit, :index]
  before_action :authenticate_user!
  before_action :is_admin?

  def index
    @users = User.all
  end

  def update
    id = params["edit_user"]
    user = User.find(id)
    if user.update(user_params)
      flash[:notice] = "更新成功!"
      redirect_to admin_users_path
    end
  end

  private

  def is_admin?
    @user = current_user
    @user.roles.pluck('name').include? "admin"
  end

  def user_params
    params.require(:user).permit(:role_ids=>[]
                                )
  end

  def correct_user
    @user = current_user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout "application"

  before_action :correct_user, only: [:edit, :update]
  before_action :authenticate_user!, except: [:index, :clause, :contact, :send_mail]
  before_action :find_user, only: [:show, :edit, :update, :upload]
  
  def index
    @users = User.all
  end

  def show
    # @photos = @user.photos.all
  end

  def edit
  end

  def update
    if user_language_params
      for language in user_language_params.keys
        language_id = Language.all.find_by(name: language).id
        level = user_language_params[language]
        
        if @user.user_language_ships.find_by(language_id: language_id)
          ship = @user.user_language_ships.find_by(language_id: language_id)
          ship.update(:level => level)
        else
          @user.user_language_ships.create(language_id: language_id, level: level)
        end
      end
    end
    
    if @user.update(user_params)
      flash[:notice] = "更新成功!"
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def destroy
  end

  def become_a_local_pal
    
  end

  private

  def find_user
    @user = User.find_by_id(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :nick_name, :profession, :head_shot,
                                 :description_English, :description_Chinese,
                                 :availability, :travel_footprints,
                                 :familiar_areas, :facebook_url, 
                                 :country, :phone_number, :birthday, :gender,
                                 :social_media_id,
                                 :interest_ids =>[],
                                 :language_ids =>[],
                                )
  end

  def user_language_params
    params.require(:user).permit( :Mandarin, :English, :Japanese, :Cantonese,
                                  :Taiwanese, :Korean, :Spanish, :French,
                                  :German, :others,
                                )
  end

  def correct_user
    @user = current_user
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
Users
<div class="container">
<div class="row">
  <div class="col-md-10">
    <table class="table" id="admin_users_table">
      <tr>
        <td>id</td>
        <td>email</td>
        <td>role</td>
        <td>edit_role</td>
      </tr
      <% @users.each do |user|%>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.email %></td>
          <td>
            <% user.roles.each do |role|%>
              <% if role.name == "admin"%>
                <%= link_to role.name,"", :class => "btn btn-info"%>
              <%elsif role.name == "tour_guide"%>
                <%= link_to role.name,"", :class => "btn btn-warning"%>
              <%end%>

            <%end%>

            <div class="form-group user-role-form" id="check-box-<%=user.id%>">
              <%=form_for user, :url => admin_user_path(user, :edit_user => user.id), :method => :PATCH do |f| %>
                <h3>
                <%= f.collection_check_boxes :role_ids, Role.all, :id, :name%>
                </h3>
                <br>
                <%= f.submit "確認", class: "btn btn-primary form-control" %>
              <%end%>
            </div>
          </td>
          <td>
            <button class="btn btn-success btn-edit-user-role" user-id="<%=user.id%>">Edit</button> 
          </td>
        </tr>
      <% end %>
    </table> 
  </div>
</div>
</div>

<script type="text/javascript">
  $( document ).ready(function() {
    $(".user-role-form").hide();
  });

  $("#admin_users_table .btn-edit-user-role").click(function(){
    $(".user-role-form").hide();
    var user_id = $(this).attr("user-id");
    var check_box_id = "#check-box-" + user_id;
    $(check_box_id).show();

  });
</script>>