config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'events#index'

  resources :events do
    
  end

  resources :users do
    resources :orders

    member do
      get :become_a_local_pal
    end
  end

  namespace :admin do
    resources :users
    resources :orders
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jdpal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="index-title" class="col-md-6 col-md-offset-2 text-center">
  <%= link_to "JDPal", events_path, class:"s4repeaterButton"%>
  <%= link_to "Become a Local Pal", "", class:"s4repeaterButton"%>
  <%= link_to "Blog", "http://jdpal2016.wix.com/home#!blog-1/fkwmw", class:"s4repeaterButton"%>
</div>

<% if current_user %>
  <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
  <%= link_to('修改密碼', edit_registration_path(:user)) %>
<% else %>
  <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, :class =>"btn btn-info" %>
  <%= link_to('註冊', new_registration_path(:user)) %> |
  <%= link_to('登入', new_session_path(:user)) %>
<% end %>

<% if current_user %>
<%= current_user.email %>
<% end %>

<hr>

<div class="container">
  <h1>後台管理</h1>
  <%=link_to "管理使用者", admin_users_path, :class => "btn btn-info btn-lg"%>
  <%=link_to "管理訂單", admin_orders_path, :class => "btn btn-warning btn-lg"%>
  <br>
  <%= yield %>
</div>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jdpal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%if flash[:notice].present? %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <%end%>
  <%if flash[:alert].present? %>
    <div class="alert alert-danger" role="alert">
      <%= flash[:alert] %>
    </div>
  <%end%>

  <div class="container" id="header-container">
    <div class="pull-left">
      <%= link_to "JDpal Admin", admin_users_path%>
    </div>
    <div id="index-title" class="col-md-6 col-md-offset-2 text-center">
      <%= link_to "JDPal", events_path, class:"s4repeaterButton"%>
      
      <% if current_user%>
        <%= link_to "Become a Local Pal", become_a_local_pal_user_path(current_user.id), class:"s4repeaterButton"%>
      <% else%>
        <!-- Todo redirect to register-->
        <%= link_to "Become a Local Pal", "", class:"s4repeaterButton"%>
      <%end%>
      
      <%= link_to "Blog", "http://jdpal2016.wix.com/home#!blog-1/fkwmw", class:"s4repeaterButton"%>
    </div>
    <div class="pull-right">
      <% if current_user %>
        <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
        <%= link_to('修改密碼', edit_registration_path(:user)) %>
      <% else %>
        <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, :class =>"btn btn-info" %>
        <%# link_to('註冊', new_registration_path(:user)) %>
        <%# link_to('登入', new_session_path(:user)) %>
      <% end %>
    </div>
    
    <% if current_user %>
      <div class="pull-right" style="font-size: 20px; margin: 10px;">
        <%= link_to image_tag("#{current_user.head_shot}", size: "40")+ current_user.name, user_path(current_user)%>
      </div>
    
    <% end %>
  </div>
  
  <div class="container" id="main-container">
    <%= yield %>
  </div>

</body>
</html>